cargo-features = ["strip"]

[package]
name = "gtk-icon-debloat"
version = "1.0.0"
edition = "2018"

[profile.release]
strip = true
panic = "abort"
codegen-units = 1
opt-level = "z"
lto = true

[dependencies]
clap = "3.0.0-beta.5"

# Logging
log = "0.4"
fern = "0.6"
chrono = "0.4"